# Generated by Django 3.2.16 on 2022-10-12 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221012_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
