# Generated by Django 3.2.16 on 2022-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221012_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='average_grade',
            new_name='grades',
        ),
        migrations.RemoveField(
            model_name='task',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='task',
            field=models.ManyToManyField(to='api.Task'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
