# Generated by Django 3.2.16 on 2022-10-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
