# Generated by Django 3.2.16 on 2022-10-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_id',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='task',
        ),
        migrations.RemoveField(
            model_name='course',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_file',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_image',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_text',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.task'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='api.chapter'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecturefile',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.lecture'),
        ),
        migrations.AddField(
            model_name='lectureimage',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.lecture'),
        ),
        migrations.AddField(
            model_name='task',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.chapter'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='task',
        ),
        migrations.AddField(
            model_name='grade',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.task'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.Course'),
        ),
        migrations.DeleteModel(
            name='LectureText',
        ),
    ]
