# Generated by Django 3.2.16 on 2022-10-17 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20221016_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='data',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
