# Generated by Django 3.2.16 on 2022-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='course_author',
            field=models.BooleanField(default=False),
        ),
    ]
