# Generated by Django 3.2.16 on 2022-10-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_comment_course_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course_author',
            new_name='is_course_author',
        ),
    ]
