# Generated by Django 3.2.16 on 2022-10-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20221018_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSolution',
            new_name='Solution',
        ),
    ]
