# Generated by Django 3.2.16 on 2022-10-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_tasksolution_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.course'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='grade',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
