# Generated by Django 3.2.16 on 2022-10-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_averagecoursegrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagecoursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.course'),
        ),
        migrations.AlterField(
            model_name='averagecoursegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
