# Generated by Django 3.2.16 on 2022-10-22 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20221022_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='grade',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
